baseURL: "https://example.com/"
languageCode: "en-us"
title: "East Asia Bitcoin Apprenticeship"
theme: "ananke"

params:
  background_color_class: "bg-black"

languages:
  en:
    title: "East Asia Bitcoin Apprenticeship"
    weight: 1
    contentDir: "content/en"
    menu:
      main:
      - identifier: about
        name: about
        url: /about/
        weight: 10
      - identifier: apply
        name: apply
        url: /apply/
        weight: 10
  한글:
    title: "동아시아 비트코인 인턴쉽"
    weight: 2
    contentDir: "content/ko"
    menu:
      main:
      - identifier: about
        name: 소개
        url: /한글/about/
        weight: 10
      - identifier: apply
        name: 지원하기
        url: /한글/apply/
        weight: 10
